More pfSense-upgrade BE support improvements

diff --git a/sysutils/pfSense-upgrade/files/pfSense-upgrade b/sysutils/pfSense-upgrade/files/pfSense-upgrade
--- a/sysutils/pfSense-upgrade/files/pfSense-upgrade
+++ b/sysutils/pfSense-upgrade/files/pfSense-upgrade
@@ -151,52 +151,57 @@ _exit() {
 	exit ${_rc}
 }
 
-# returns the current root filesystem
+# Returns the current root filesystem
 _be_get_rootfs() {
 	/sbin/mount | /usr/bin/awk '/ \/ / {print $1}'
 }
 
-# returns the ZFS pool that holds the root filesystem
+# Returns the ZFS pool that holds the root filesystem
 _be_get_pool() {
-	echo $( _be_get_rootfs ) | /usr/bin/awk -F '/' '{print $1}'
+	echo "$( _be_get_rootfs )" | /usr/bin/awk -F '/' '{print $1}'
 }
 
-# translates a BE name into a dataset path
+# Translates a BE name into a dataset path
 _be_name_to_ds() {
 	local _name="${1}"
 	local _beds="$( echo $( _be_get_rootfs ) | /usr/bin/awk -F '/' '{print $2}' )"
 	echo "$( _be_get_pool )/${_beds}/${_name}"
 }
 
-# returns the version of a package
+# Returns the version of a package
 _get_pkg_version() {
 	local _pkg="${1}"
 	_pkg query %v "${_pkg}" | head -n1
 }
 
-# returns the active BE
+# Returns the active dataset
+_be_get_active_ds() {
+	_be_name_to_ds "$( _be_get_active )"
+}
+
+# Returns the active BE
 _be_get_active() {
 	/sbin/bectl list -H | /usr/bin/awk 'index($2, "N") {print $1}' | head -n1
 }
 
-# sanity check for BE support (e.g. fails on UFS systems)
+# Sanity check for BE support (e.g. fails on UFS systems)
 _be_check() {
 	/sbin/bectl check 1>/dev/null 2>&1
 }
 
-# activate a given BE by name
+# Activate a given BE by name
 _be_activate() {
 	local _name="${1}"
 	/sbin/bectl activate "${_name}" 1>/dev/null 2>&1
 }
 
-# create a given BE by name
+# Create a given BE by name
 _be_create() {
 	local _name="${1}"
 	/sbin/bectl create -r "${_name}" 1>/dev/null 2>&1
 }
 
-# set a zfs property
+# Set a ZFS property
 _zfs_set_property() {
 	local _target="${1}"
 	local _property="${2}"
@@ -204,29 +209,67 @@ _zfs_set_property() {
 	/sbin/zfs set "${_property}=${_value}" "${_target}" 1>/dev/null 2>&1
 }
 
-# prepare system to upgrade by creating a BE before touching the
-# current environment. we also set some useful ZFS user properties
-# here as well for the UI
+# Get a ZFS property
+_zfs_get_property() {
+	local _target="${1}"
+	local _property="${2}"
+	/sbin/zfs get -H -o value "${_property}" "${_target}" 2>/dev/null
+}
+
+# Sanity check that we have a valid rollback BE
+_be_has_valid_rollback_be() {
+	local _active_ds="$( _be_get_active_ds )"
+	local _rollback_be="$( _zfs_get_property "${_active_ds}" pfsense:rollbackbe )"
+	/sbin/zfs list "$( _be_name_to_ds "${_rollback_be}" )" 1>/dev/null 2>&1
+}
+
+# Check if we are in the process of upgrading. This flag is reset at startup
+_be_is_upgrading() {
+	local _active_ds="$( _be_get_active_ds )"
+	local _is_upgrading="$( _zfs_get_property "${_active_ds}" pfsense:isupgrading )"
+	[ "${_is_upgrading}" = "yes" ]
+}
+
+# Prepare the system to upgrade by creating a BE before touching the
+# current environment. We also set some useful ZFS user properties
+# here as well for displaying in the UI.
 _be_prep_upgrade() {
 	if _be_check; then
+		# We need to ensure that we only run this once or unless absolutely
+		# necessary. Because pfSense-upgrade self-updates, it is possible
+		# that this code is executed more than once. We only want one
+		# rollback BE to be created per system upgrade.
+		if _be_is_upgrading; then
+			return 0;
+		fi
+
+		_echo ">>> Creating automatic pre-upgrade boot environment..."
+
 		local _timestamp="$( date "+%Y%m%d%H%M%S" )"
 		local _be_name="$( _be_get_active )_${_timestamp}"
-		local _ds_name="$( _be_name_to_ds ${_be_name} )"
 
-		_echo ">>> Creating automatic pre-upgrade boot environment... "
 		_be_create ${_be_name}
-		_rc=$?
-		if [ ${_rc} -eq 0 ]; then
-			_zfs_set_property "${_ds_name}" pfsense:version "$( _get_pkg_version pfSense-base )"
-			_zfs_set_property "${_ds_name}" pfsense:description "Automatically created by system update"
+		if [ $? -eq 0 ]; then
+			local _active_ds="$( _be_get_active_ds )"
+			local _ds_name="$( _be_name_to_ds ${_be_name} )"
+
+			_zfs_set_property ${_active_ds} pfsense:isupgrading yes
+			_zfs_set_property ${_active_ds} pfsense:rollbackbe ${_be_name}
+
+			_zfs_set_property ${_ds_name} pfsense:description "Automatically created by system update"
+			_zfs_set_property ${_ds_name} pfsense:version "$( _get_pkg_version ${product}-base )"
 		fi
-		return ${_rc}
+		
+		# A test to be sure we really created a valid rollback BE
+		if !(_be_has_valid_rollback_be); then
+			return 1
+		fi
 	fi
 	return 0
 }
 
-# prepare system to reboot by ensuring we are rebooting into the
-# BE that is actively being upgraded
+# Prepare the system to reboot by ensuring that we are rebooting into the
+# BE that is actively being upgraded.
 _be_prep_reboot() {
 	if _be_check; then
 		local _name="$( _be_get_active )"
